global:
  scrape_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  - job_name: 'eureka-server'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - eureka-server:8761

  - job_name: 'gateway'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - gateway:8080

  - job_name: 'ingest-service-vm1'
    metrics_path: /actuator/prometheus
    eureka_sd_configs:
      - server: http://eureka-server:8761/eureka
        refresh_interval: 30s
    relabel_configs:
      - source_labels: [__meta_eureka_app_name]
        target_label: application
      - source_labels: [__meta_eureka_app_instance_id]
        target_label: instance
      - source_labels: [__meta_eureka_app_name]
        action: keep
        regex: INGEST-SERVICE-VM1

  - job_name: 'ingest-service-vm2'
    metrics_path: /actuator/prometheus
    eureka_sd_configs:
      - server: http://eureka-server:8761/eureka
        refresh_interval: 30s
    relabel_configs:
      - source_labels: [__meta_eureka_app_name]
        target_label: application
      - source_labels: [__meta_eureka_app_instance_id]
        target_label: instance
      - source_labels: [__meta_eureka_app_name]
        action: keep
        regex: INGEST-SERVICE-VM2

  - job_name: 'consumer-worker'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - consumer-worker:8081

  - job_name: 'monitoring-service'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - monitoring-service:8082

  - job_name: 'settlement-worker'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - settlement-worker:8084

  - job_name: 'refund-worker'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - refund-worker:8085
