global:
  scrape_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  - job_name: 'eureka-server'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - eureka-server:8761

  - job_name: 'gateway'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - gateway:8080

  - job_name: 'ingest-service'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - ingest-service:8080

  - job_name: 'consumer-worker'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - consumer-worker:8081

  - job_name: 'monitoring-service'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - monitoring-service:8082

  - job_name: 'settlement-worker'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - settlement-worker:8084

  - job_name: 'refund-worker'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - refund-worker:8085
