apiVersion: 1

datasources:
  - name: MariaDB
    type: mysql
    uid: mariadb
    access: proxy
    url: mariadb:3306
    database: paydb
    user: payuser
    jsonData:
      maxOpenConns: 0
      maxIdleConns: 2
      connMaxLifetime: 14400
    secureJsonData:
      password: paypass
    editable: false
